### ISSUE TITLE
생성 창에서 틀을 선택한 다음, 다른 항목을 선택하면 틀이 유지됨

### ISSUE THREAD

**Issue by Ubinquitous** [Original-Gimchi/BUMAWIKI_WEB_V1#3]
### 🐞 Describe

생성 창의 문서 항목에서 틀을 선택한 후, 다른 항목을 재선택하면 틀이 계속 남아있는 버그가 발생합니다.

### 🌏 Environment

macOS

**Comment by 5ewon** [comment]
틀문서의 작성 내용이 남아 있는 상태에서 다른 독스 타입으로 변경 시 제목과 내용이 초기화되도록 수정하였습니다.
